name: saftp
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - pip
  - python=3.9.19
  - cuda
  - packaging
  - pytorch==2.5.1
  - torchvision==0.20.1
  - pytorch-cuda=11.8
  - pip:
      - omegaconf
      - torchmetrics==0.10.3
      - autogluon==1.1.1
      - fvcore
      - iopath
      - xformers==0.0.28.post3
      - huggingface-hub==0.20.2
      - transformers==4.46.3
      - triton==3.1.0
      - h5py
      - numpy
      - pandas
      - pillow
      - tqdm
      - einops
      - webdataset
      - matplotlib
      - lifelines
      - scikit-survival
      - scikit-learn
      - tensorboard
      - fairscale
      - wandb
      - timm>=1.0.3
      - packaging==23.2
      - ninja==1.11.1.1
      - transformers==4.36.2
      - flash-attn==2.5.8
      - monai
      - openslide-python
      - scikit-image
